<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ajiMLT" nsURI="http://www.fh-dortmund.de/idial/ajiML/tech" nsPrefix="ajiML">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ajiML" value="ajiML.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalServiceT" eSuperTypes="ajiML.ecore#//FunctionalService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" lowerBound="1"
        eType="#//EGenerator" defaultValueLiteral="SpringCloud"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="database" lowerBound="1"
        eType="#//EDatabase" defaultValueLiteral="MongoDB"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscoveryServiceT" eSuperTypes="ajiML.ecore#//DiscoveryService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" lowerBound="1"
        eType="#//EGenerator" defaultValueLiteral="SpringCloud"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIServiceT" eSuperTypes="ajiML.ecore#//APIService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" lowerBound="1"
        eType="#//EGenerator" defaultValueLiteral="SpringCloud"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationServiceT" eSuperTypes="ajiML.ecore#//ConfigurationService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" lowerBound="1"
        eType="#//EGenerator" defaultValueLiteral="SpringCloud"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityServiceT" eSuperTypes="ajiML.ecore#//SecurityService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" lowerBound="1"
        eType="#//EGenerator" defaultValueLiteral="SpringCloud"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="certificatePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="certificatePassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="KeyPairName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInterfaceT" eSuperTypes="ajiML.ecore#//ServiceInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanism" lowerBound="1"
        eType="#//ECommunicationMechanism" defaultValueLiteral="RESTfulHTTP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserManagementServiceT" eSuperTypes="ajiML.ecore#//UserManagementService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" lowerBound="1"
        eType="#//EGenerator" defaultValueLiteral="SpringCloud"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EGenerator">
    <eLiterals name="SpringCloud"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ECommunicationMechanism">
    <eLiterals name="RESTfulHTTP"/>
    <eLiterals name="PublishSubscribe" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EDatabase">
    <eLiterals name="MongoDB"/>
    <eLiterals name="MySQL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EMultiplicity">
    <eLiterals name="ONE"/>
    <eLiterals name="MANY" value="1"/>
  </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemT" eSuperTypes="ajiML.ecore#//System">
  </eClassifiers>
</ecore:EPackage>
