<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ajil" nsURI="http://www.example.org/ajil" nsPrefix="ajil">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="ECommunicationMechanism">
    <eLiterals name="RESTfulHTTP"/>
    <eLiterals name="PublishSubscribe" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EMultiplicity">
    <eLiterals name="ONE"/>
    <eLiterals name="MANY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="#//EMultiplicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="mySystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Microservice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Microservice" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueServiceName uniqueServicePort"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="uniqueServiceName" value="Microservice.allInstances()->forAll(s : Microservice | s &lt;> self implies s.name &lt;> self.name)"/>
      <details key="uniqueServicePort" value="Microservice.allInstances()->forAll(p : Microservice | p &lt;> self implies p.port &lt;> self.port)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myService"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="8888"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadBalanced" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="circuitBreaker" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructureService" abstract="true"
      eSuperTypes="#//Microservice"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalService" eSuperTypes="#//Microservice">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noSelfDependency"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="noSelfDependency" value="self.serviceDependencies->forAll(i : ServiceInterface | self.providedInterfaces->excludes(i))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//DomainModel" containment="true" eOpposite="#//DomainModel/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" lowerBound="1"
        upperBound="-1" eType="#//ServiceInterface" containment="true" eOpposite="#//ServiceInterface/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceDependencies" upperBound="-1"
        eType="#//ServiceInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discoveredBy" eType="#//DiscoveryService"
        eOpposite="#//DiscoveryService/knownFunctionalServices"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuredBy" eType="#//ConfigurationService"
        eOpposite="#//ConfigurationService/storedConfigurations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscoveryService" eSuperTypes="#//InfrastructureService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="knownFunctionalServices"
        upperBound="-1" eType="#//FunctionalService" eOpposite="#//FunctionalService/discoveredBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knownApiServices" upperBound="-1"
        eType="#//APIService" eOpposite="#//APIService/discoveredBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knownConfigurationServices"
        upperBound="-1" eType="#//ConfigurationService" eOpposite="#//ConfigurationService/discoveredBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIService" eSuperTypes="#//InfrastructureService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exposedServices" upperBound="-1"
        eType="#//ServiceInterface" eOpposite="#//ServiceInterface/exposedToGateways"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discoveredBy" eType="#//DiscoveryService"
        eOpposite="#//DiscoveryService/knownApiServices"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationService" eSuperTypes="#//InfrastructureService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="discoveredBy" eType="#//DiscoveryService"
        eOpposite="#//DiscoveryService/knownConfigurationServices"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storedConfigurations" eType="#//FunctionalService"
        eOpposite="#//FunctionalService/configuredBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInterface">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueInterfaceName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="uniqueInterfaceName" value="ServiceInterface.allInstances()->forAll(s : ServiceInterface | s &lt;> self implies s.name &lt;> self.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myInterface"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanism" lowerBound="1"
        eType="#//ECommunicationMechanism"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abilities" upperBound="-1"
        eType="#//Ability" containment="true" eOpposite="#//Ability/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exposedToGateways" upperBound="-1"
        eType="#//APIService" changeable="false" eOpposite="#//APIService/exposedServices"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//FunctionalService"
        changeable="false" transient="true" eOpposite="#//FunctionalService/providedInterfaces"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueDomainName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="uniqueDomainName" value="DomainModel.allInstances()->forAll(d : DomainModel | d &lt;> self implies d.name &lt;> self.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myDomainModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true" eOpposite="#//Entity/domainModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//FunctionalService"
        changeable="false" eOpposite="#//FunctionalService/domain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sealedDomainInheritance uniqueEntityName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="sealedDomainInheritance" value="if self.parent.oclIsUndefined() then true else if self.parent.domainModel = self.domainModel then true else false &#xA;endif endif"/>
      <details key="uniqueEntityName" value="Entity.allInstances()->forAll(ent : Entity | ent &lt;> self implies ent.name &lt;> self.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//PrimitiveDataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation" containment="true" eOpposite="#//Relation/source"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModel" lowerBound="1"
        eType="#//DomainModel" changeable="false" transient="true" eOpposite="#//DomainModel/entities"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//Multiplicity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sealedDomain noSelfRelation"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="sealedDomain" value="self.source.domainModel = self.target.domainModel"/>
      <details key="noSelfRelation" value="self.source &lt;> self.target"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myRelation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Entity" changeable="false" eOpposite="#//Entity/relations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ability" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueCapabilityName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="uniqueCapabilityName" value="Ability.allInstances()->forAll(a : Ability | a &lt;> self implies a.name &lt;> self.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//ServiceInterface"
        changeable="false" transient="true" eOpposite="#//ServiceInterface/abilities"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Create" eSuperTypes="#//Ability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Read" eSuperTypes="#//Ability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiRead" eSuperTypes="#//Ability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Update" eSuperTypes="#//Ability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delete" eSuperTypes="#//Ability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Custom" eSuperTypes="#//Ability"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveDataType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//PrimitiveDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//PrimitiveDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//PrimitiveDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="Float"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//PrimitiveDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Char" eSuperTypes="#//PrimitiveDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="myChar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="Char"/>
  </eClassifiers>
</ecore:EPackage>
